
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plant_dex_db
    driver-class-name: org.postgresql.Driver
    username: rf2
    password: rf2
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 3000
